In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('implementation-of-sex-education')
jovian.set_colab_id('1m2qQTY29tJ3ZqLKp_j-LsHJnGBRHJsCd')

     |████████████████████████████████| 68 kB 3.4 MB/s
  Building wheel for uuid (setup.py) ... done

# implementation-of-sex-education

Use the "Run" button to execute the code.

## Implementation of Sex Education Exploratory Data Analysis
Todo - talk about EDA
Todo - talk about the dataset (source, what it contains, how is it useful)
- Philippine Statistics Authority
- Data about Teenage Pregnancy
- Can be used to highlight the importance of Sex Education

#START

##Download the Data

In [ ]:
#Download the data and assign to data_set variable names
data_set1 = './Summary of Birth Statistics in the Philippines (1903-2018).csv'
data_set2 = './Number of Live Births M&F 2012.csv'
data_set3 = './Number of Live Births M&F 2013.csv'
data_set4 = './Number of Live Births M&F 2014.csv'
data_set5 = './Number of Live Births M&F 2015.csv'
data_set6 = './Number of Live Births M&F 2016.csv'
data_set7 = './Number of Live Births M&F 2017.csv'
data_set8 = './Number of Live Births M&F 2018.csv'
data_set9 = './Number of Live Births M&F 2019.csv'
data_set10 = './APIS Reasons for not Attending.csv'
data_set11 = './/APIS Schooling status.csv'
data_set12 = './NDHS_Current use of contraception.csv'
data_set13 = './NDHS_Knowledge of HIV prevention methods.csv'

##Data Preparation and Cleaning
1. Load the files using Pandas
2. Look at some information about the data & the columns
3. Fix any missing or incorrect values

In [ ]:
#import pandas library
import pandas as pd

In [ ]:
#making DataFrames from downloaded csv files
df1 = pd.read_csv(data_set1)
df2 = pd.read_csv(data_set2)
df3 = pd.read_csv(data_set3)
df4 = pd.read_csv(data_set4)
df5 = pd.read_csv(data_set5)
df6 = pd.read_csv(data_set6)
df7 = pd.read_csv(data_set7)
df8 = pd.read_csv(data_set8)
df9 = pd.read_csv(data_set9)
df10 = pd.read_csv(data_set10)
df11 = pd.read_csv(data_set11)
df12 = pd.read_csv(data_set12)
df13 = pd.read_csv(data_set13)

In [ ]:
#show entire df (change # to check other df)
print(df1.to_string())

       Yr  Population (1000)  # of L.Births  Crude B.R.  Birth Increase/Decrease  Percentage Change
0    2018           105755.0      1668120.0        15.8                 -32498.0               -1.9
1    2017           104921.0      1700618.0        16.2                 -30671.0               -1.8
2    2016           103243.0      1731289.0        16.8                 -13478.0               -0.8
3    2015           100981.0      1744767.0        17.2                  -4090.0               -0.2
4    2014            99880.0      1748857.0        17.5                 -12745.0               -0.7
5    2013            98197.0      1761602.0        17.9                 -28765.0               -1.6
6    2012            96511.0      1790367.0        18.6                  43683.0                2.5
7    2011            94824.0      1746684.0        18.4                 -36297.0               -2.0
8    2010            92335.0      1782981.0        19.1                  37397.0                2.1
9    2009            92227.0      1745584.0        18.9                 -38732.0               -2.2
10   2008            90457.0      1784316.0        19.7                  34438.0                2.0
11   2007            88548.0      1749878.0        19.7                  86849.0                5.2
12   2006            86973.0      1663029.0        19.1                 -25889.0               -1.5
13   2005            84241.0      1688918.0        19.8                 -22076.0               -1.3
14   2004            82663.0      1710994.0        20.5                  41552.0                2.5
15   2003            81081.0      1669442.0        20.4                   2669.0                0.2
16   2002            79503.0      1666773.0        20.8                 -47320.0               -2.8
17   2001            77926.0      1714093.0        21.8                 -52347.0               -3.0
18   2000            76507.0      1766440.0        23.0                 153105.0                9.5
19   1999            74746.0      1613335.0        21.6                 -19524.0               -1.2
20   1998            73147.0      1632859.0        22.3                 -20377.0               -1.2
21   1997            71549.0      1653236.0        23.1                  44768.0                2.8
22   1996            69951.0      1608468.0        23.0                 -36575.0               -2.2
23   1995            68617.0      1645043.0        24.0                     32.0                0.0
24   1994            68624.0      1645011.0        24.0                 -35885.0               -2.1
25   1993            66982.0            NaN        25.1                  -3499.0               -0.2
26   1992            65339.0      1684395.0        25.8                  41099.0                2.5
27   1991            63729.0      1643296.0        25.8                  12227.0                0.7
28   1990            60703.0      1631069.0        26.9                  65815.0                4.2
29   1989            60097.0      1565254.0        26.0                   -118.0                0.0
30   1988            58721.0      1565372.0        26.7                 -17097.0               -1.1
31   1987            57356.0      1582469.0        27.6                  88474.0                5.9
32   1986            56004.0      1493995.0        26.7                  56841.0                4.0
33   1985            54668.0      1437154.0        26.3                 -41051.0               -2.8
34   1984            53351.0      1478205.0        27.7                 -28151.0               -1.9
35   1983            52055.0      1506356.0        28.9                  31865.0                2.2
36   1982            50783.0      1474491.0        29.0                  13287.0                0.9
37   1981            49536.0      1461204.0        29.5                   4344.0                0.3
38   1980            48098.0      1456860.0        30.3                  27046.0                1.9
39   1979            46592.0      1429814.0        30.7                  42226.0                3.0
40   1978            45498.0      1387588.0        30.5                  42752.0                3.2
41   1977            44417.0      1344836.0        30.3                  29976.0                2.3
42   1976            43338.0      1314860.0        30.3                  91023.0                7.4
43   1975            42071.0      1223837.0        29.1                 142764.0               13.2
44   1974            41279.0      1081073.0        26.2                  31783.0                3.0
45   1973            40123.0      1049290.0        26.2                  80905.0                8.4
46   1972            38991.0       968385.0        24.8                   4636.0                0.5
47   1971            37902.0       963749.0        25.4                  -3013.0               -0.3
48   1970            36684.0       966762.0        26.4                  20009.0                2.1
49   1969            35774.0       946753.0        26.5                  48183.0                5.4
50   1968            34728.0       898570.0        25.9                  58268.0                6.9
51   1967            33713.0       840302.0        24.9                  16960.0                2.1
52   1966            32727.0       823342.0        25.2                  27927.0                3.5
53   1965            31770.0       795415.0        25.0                  -7233.0               -0.9
54   1964            30841.0       802648.0        26.0                  15950.0                2.0
55   1963            29937.0       786698.0        26.3                  11552.0                1.5
56   1962            29064.0       775146.0        26.7                 127300.0               19.6
57   1961            28214.0       647846.0        23.0                  -1805.0               -0.3
58   1960            27088.0       649651.0        24.0                  32758.0                5.3
59   1959            26584.0       616893.0        23.2                 132301.0               27.3
60   1958            25795.0       484592.0        18.8                 -29610.0               -5.8
61   1957            25030.0       514202.0        20.5                 -28047.0               -5.2
62   1956            24288.0       542249.0        22.3                -192512.0              -26.2
63   1955            23568.0       734761.0        31.2                  32099.0                4.6
64   1954            22869.0       702662.0        30.7                 234173.0               50.0
65   1953            21039.0       468489.0        22.3                -182236.0              -28.0
66   1952            20646.0       650725.0        31.5                  13461.0                2.1
67   1951            20260.0       637264.0        31.5                  -5208.0               -0.8
68   1950            19881.0       642472.0        32.3                  33334.0                5.5
69   1949            19509.0       642472.0        31.2                   6723.0                1.1
70   1948            19234.0       609415.0        31.3                 330189.0              121.3
71   1947            18786.0       272226.0        14.5                -261057.0              -49.0
72   1946            18434.0       533283.0        28.9                      NaN                NaN
73   1945                NaN            NaN         NaN                      NaN                NaN
74   1944                NaN            NaN         NaN                      NaN                NaN
75   1943                NaN            NaN         NaN                      NaN                NaN
76   1942                NaN            NaN         NaN                      NaN                NaN
77   1941                NaN            NaN         NaN                      NaN                NaN
78   1940            16460.0       535117.0        32.5                  12685.0                2.4
79   1939            16000.0       522432.0        32.7                  10043.0                2.0
80   1938            15814.0       512389.0        32.4                  -1371.0               -0.3
81   1937            15445.0       513760.0        33.3                  28634.0                5.9
82   1936            15084.0       485126.0        32.2                  23716.0                5.1
83   1935            14731.0       461410.0        31.3                  13672.0                3.1
84   1934            14387.0       447738.0        31.1                 -11944.0               -2.6
85   1933            14051.0       459682.0        32.7                  12742.0                2.9
86   1932            13724.0       446940.0        32.6                   6781.0                1.5
87   1931            13405.0       440159.0        32.8                  10914.0                2.5
88   1930            13094.0       429245.0        32.8                    249.0                0.1
89   1929            12792.0       428996.0        33.5                   6280.0                1.5
90   1928            12498.0       422716.0        33.8                   8359.0                2.0
91   1927            12212.0       414357.0        33.9                  13918.0                3.5
92   1926            11935.0       400439.0        33.6                  15021.0                3.9
93   1925                NaN            NaN         NaN                      NaN                NaN
94   1924                NaN            NaN         NaN                      NaN                NaN
95   1923            11152.0       385418.0        34.6                  11912.0                3.2
96   1922            10908.0       373506.0        34.2                   9074.0                2.5
97   1921            10673.0       364432.0        34.1                  13237.0                3.8
98   1920            10445.0       351195.0        33.6                  44363.0               14.5
99   1919            10324.0       306832.0        29.7                 -38919.0              -11.3
100  1918            10314.0       345751.0        33.5                  -7532.0               -2.1
101  1917             9836.0       353283.0        35.9                  12654.0                3.7
102  1916             9542.0       340629.0        35.7                  13423.0                4.1
103  1915             9269.0       327206.0        35.3                 -20131.0               -5.8
104  1914             9017.0       347337.0        38.5                  31281.0                9.9
105  1913             8786.0       316056.0        36.0                  25061.0                8.6
106  1912             8576.0       290995.0        33.9                 -11860.0               -3.9
107  1911             8387.0       302855.0        36.1                  12645.0                4.4
108  1910             8220.0       290210.0        35.3                  55484.0               23.6
109  1909             8095.0       234726.0        29.0                 -43643.0              -15.7
110  1908             7964.0       278369.0        35.0                  20359.0                7.9
111  1907             7844.0       258010.0        32.9                  42714.0               19.8
112  1906             7761.0       215296.0        27.7                 -29290.0              -12.0
113  1905             7699.0       244586.0        31.8                  28410.0               13.1
114  1904             7659.0       216176.0        28.2                 -68624.0              -24.1
115  1903             7635.0       284800.0        37.3                      NaN                NaN

In [ ]:
#check for datatype of each column (change # to check other df)
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Yr                       116 non-null    int64
 1   Population (1000)        109 non-null    float64
 2   # of L.Births            108 non-null    float64
 3   Crude B.R.               109 non-null    float64
 4   Birth Increase/Decrease  107 non-null    float64
 5   Percentage Change        107 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 5.6 KB
None

###DF1 cleaning

In [ ]:
#check for null values in df1
bool_series1=pd.isnull(df1["# of L.Births"] + df1["Population (1000)"] + df1["Birth Increase/Decrease"] + df1["Crude B.R."] + df1["Percentage Change"])
bool_series2=pd.isnull(df1["Yr"])

In [ ]:
#display data w/ null values from df1
df1[bool_series1]

,Yr,Population (1000),# of L.Births,Crude B.R.,Birth Increase/Decrease,Percentage Change
25,1993,66982.0,NaN,25.1,-3499.0,-0.2
72,1946,18434.0,533283.0,28.9,NaN,NaN
73,1945,NaN,NaN,NaN,NaN,NaN
74,1944,NaN,NaN,NaN,NaN,NaN
75,1943,NaN,NaN,NaN,NaN,NaN
76,1942,NaN,NaN,NaN,NaN,NaN
77,1941,NaN,NaN,NaN,NaN,NaN
93,1925,NaN,NaN,NaN,NaN,NaN
94,1924,NaN,NaN,NaN,NaN,NaN
115,1903,7635.0,284800.0,37.3,NaN,NaN

In [ ]:
df1[bool_series2]

Empty DataFrame
Columns: [Yr, Population (1000), # of L.Births, Crude B.R., Birth Increase/Decrease, Percentage Change]
Index: []

In [ ]:
#drop all rows with null values in original df1
df1.dropna(inplace = True)

In [ ]:
#display cleaned df1
print(df1.to_string())

       Yr  Population (1000)  # of L.Births  Crude B.R.  Birth Increase/Decrease  Percentage Change
0    2018           105755.0      1668120.0        15.8                 -32498.0               -1.9
1    2017           104921.0      1700618.0        16.2                 -30671.0               -1.8
2    2016           103243.0      1731289.0        16.8                 -13478.0               -0.8
3    2015           100981.0      1744767.0        17.2                  -4090.0               -0.2
4    2014            99880.0      1748857.0        17.5                 -12745.0               -0.7
5    2013            98197.0      1761602.0        17.9                 -28765.0               -1.6
6    2012            96511.0      1790367.0        18.6                  43683.0                2.5
7    2011            94824.0      1746684.0        18.4                 -36297.0               -2.0
8    2010            92335.0      1782981.0        19.1                  37397.0                2.1
9    2009            92227.0      1745584.0        18.9                 -38732.0               -2.2
10   2008            90457.0      1784316.0        19.7                  34438.0                2.0
11   2007            88548.0      1749878.0        19.7                  86849.0                5.2
12   2006            86973.0      1663029.0        19.1                 -25889.0               -1.5
13   2005            84241.0      1688918.0        19.8                 -22076.0               -1.3
14   2004            82663.0      1710994.0        20.5                  41552.0                2.5
15   2003            81081.0      1669442.0        20.4                   2669.0                0.2
16   2002            79503.0      1666773.0        20.8                 -47320.0               -2.8
17   2001            77926.0      1714093.0        21.8                 -52347.0               -3.0
18   2000            76507.0      1766440.0        23.0                 153105.0                9.5
19   1999            74746.0      1613335.0        21.6                 -19524.0               -1.2
20   1998            73147.0      1632859.0        22.3                 -20377.0               -1.2
21   1997            71549.0      1653236.0        23.1                  44768.0                2.8
22   1996            69951.0      1608468.0        23.0                 -36575.0               -2.2
23   1995            68617.0      1645043.0        24.0                     32.0                0.0
24   1994            68624.0      1645011.0        24.0                 -35885.0               -2.1
26   1992            65339.0      1684395.0        25.8                  41099.0                2.5
27   1991            63729.0      1643296.0        25.8                  12227.0                0.7
28   1990            60703.0      1631069.0        26.9                  65815.0                4.2
29   1989            60097.0      1565254.0        26.0                   -118.0                0.0
30   1988            58721.0      1565372.0        26.7                 -17097.0               -1.1
31   1987            57356.0      1582469.0        27.6                  88474.0                5.9
32   1986            56004.0      1493995.0        26.7                  56841.0                4.0
33   1985            54668.0      1437154.0        26.3                 -41051.0               -2.8
34   1984            53351.0      1478205.0        27.7                 -28151.0               -1.9
35   1983            52055.0      1506356.0        28.9                  31865.0                2.2
36   1982            50783.0      1474491.0        29.0                  13287.0                0.9
37   1981            49536.0      1461204.0        29.5                   4344.0                0.3
38   1980            48098.0      1456860.0        30.3                  27046.0                1.9
39   1979            46592.0      1429814.0        30.7                  42226.0                3.0
40   1978            45498.0      1387588.0        30.5                  42752.0                3.2
41   1977            44417.0      1344836.0        30.3                  29976.0                2.3
42   1976            43338.0      1314860.0        30.3                  91023.0                7.4
43   1975            42071.0      1223837.0        29.1                 142764.0               13.2
44   1974            41279.0      1081073.0        26.2                  31783.0                3.0
45   1973            40123.0      1049290.0        26.2                  80905.0                8.4
46   1972            38991.0       968385.0        24.8                   4636.0                0.5
47   1971            37902.0       963749.0        25.4                  -3013.0               -0.3
48   1970            36684.0       966762.0        26.4                  20009.0                2.1
49   1969            35774.0       946753.0        26.5                  48183.0                5.4
50   1968            34728.0       898570.0        25.9                  58268.0                6.9
51   1967            33713.0       840302.0        24.9                  16960.0                2.1
52   1966            32727.0       823342.0        25.2                  27927.0                3.5
53   1965            31770.0       795415.0        25.0                  -7233.0               -0.9
54   1964            30841.0       802648.0        26.0                  15950.0                2.0
55   1963            29937.0       786698.0        26.3                  11552.0                1.5
56   1962            29064.0       775146.0        26.7                 127300.0               19.6
57   1961            28214.0       647846.0        23.0                  -1805.0               -0.3
58   1960            27088.0       649651.0        24.0                  32758.0                5.3
59   1959            26584.0       616893.0        23.2                 132301.0               27.3
60   1958            25795.0       484592.0        18.8                 -29610.0               -5.8
61   1957            25030.0       514202.0        20.5                 -28047.0               -5.2
62   1956            24288.0       542249.0        22.3                -192512.0              -26.2
63   1955            23568.0       734761.0        31.2                  32099.0                4.6
64   1954            22869.0       702662.0        30.7                 234173.0               50.0
65   1953            21039.0       468489.0        22.3                -182236.0              -28.0
66   1952            20646.0       650725.0        31.5                  13461.0                2.1
67   1951            20260.0       637264.0        31.5                  -5208.0               -0.8
68   1950            19881.0       642472.0        32.3                  33334.0                5.5
69   1949            19509.0       642472.0        31.2                   6723.0                1.1
70   1948            19234.0       609415.0        31.3                 330189.0              121.3
71   1947            18786.0       272226.0        14.5                -261057.0              -49.0
78   1940            16460.0       535117.0        32.5                  12685.0                2.4
79   1939            16000.0       522432.0        32.7                  10043.0                2.0
80   1938            15814.0       512389.0        32.4                  -1371.0               -0.3
81   1937            15445.0       513760.0        33.3                  28634.0                5.9
82   1936            15084.0       485126.0        32.2                  23716.0                5.1
83   1935            14731.0       461410.0        31.3                  13672.0                3.1
84   1934            14387.0       447738.0        31.1                 -11944.0               -2.6
85   1933            14051.0       459682.0        32.7                  12742.0                2.9
86   1932            13724.0       446940.0        32.6                   6781.0                1.5
87   1931            13405.0       440159.0        32.8                  10914.0                2.5
88   1930            13094.0       429245.0        32.8                    249.0                0.1
89   1929            12792.0       428996.0        33.5                   6280.0                1.5
90   1928            12498.0       422716.0        33.8                   8359.0                2.0
91   1927            12212.0       414357.0        33.9                  13918.0                3.5
92   1926            11935.0       400439.0        33.6                  15021.0                3.9
95   1923            11152.0       385418.0        34.6                  11912.0                3.2
96   1922            10908.0       373506.0        34.2                   9074.0                2.5
97   1921            10673.0       364432.0        34.1                  13237.0                3.8
98   1920            10445.0       351195.0        33.6                  44363.0               14.5
99   1919            10324.0       306832.0        29.7                 -38919.0              -11.3
100  1918            10314.0       345751.0        33.5                  -7532.0               -2.1
101  1917             9836.0       353283.0        35.9                  12654.0                3.7
102  1916             9542.0       340629.0        35.7                  13423.0                4.1
103  1915             9269.0       327206.0        35.3                 -20131.0               -5.8
104  1914             9017.0       347337.0        38.5                  31281.0                9.9
105  1913             8786.0       316056.0        36.0                  25061.0                8.6
106  1912             8576.0       290995.0        33.9                 -11860.0               -3.9
107  1911             8387.0       302855.0        36.1                  12645.0                4.4
108  1910             8220.0       290210.0        35.3                  55484.0               23.6
109  1909             8095.0       234726.0        29.0                 -43643.0              -15.7
110  1908             7964.0       278369.0        35.0                  20359.0                7.9
111  1907             7844.0       258010.0        32.9                  42714.0               19.8
112  1906             7761.0       215296.0        27.7                 -29290.0              -12.0
113  1905             7699.0       244586.0        31.8                  28410.0               13.1
114  1904             7659.0       216176.0        28.2                 -68624.0              -24.1

###DF10 cleaning

In [ ]:
#check for null values in df10
bool_series=pd.isnull(df10["M&F"] + df10["Male"] + df10["Female"])

In [ ]:
#display data w/ null values from d10
df10[bool_series]

   Reason for Not Attending School/Region/Residence  M&F Male Female
5                                         Pregnancy  1.6  NaN    3.5
13                        Too young to go to school  NaN  NaN    NaN
14                                         Bullying  0.3  0.5    NaN

In [ ]:
#replace missing values
#to complete the 100% total, the 0.1% was put on "Too young to go to school" since it was more appropriate to add there
df10.loc[13, 'Male'] = 0.1
df10.fillna(0, inplace = True)

In [ ]:
#display cleaned df10
print(df10.to_string())

              Reason for Not Attending School/Region/Residence     M&F    Male  Female
0   Population on Aged 6 to 24 Years Old (Total, in thousands)  39,978  20,491  19,487
1           # of Not Currently Attending (Total, in Thousands)   9,668   5,199   4,469
2                                                      Total %     100     100     100
3                                      Accessibility of School     0.7     0.8     0.6
4                                          Illness/ Disability     3.5       4     2.9
5                                                    Pregnancy     1.6       0     3.5
6                                                     Marriage      15     7.8    23.4
7                    High Cost of Education/ Financial Concern    11.9      14     9.5
8                                                   Employment    22.2    26.4    17.3
9       Finished Schooling or Finished Post Secondary/ College    14.6    11.2    18.7
10                                            Looking for work     6.5     7.4     5.4
11                                   Lack of Personal Interest     7.8    11.6     3.3
12               Due TO Covid-19 pandemic community quarantine     9.6    10.3     8.7
13                                   Too young to go to school       0     0.1       0
14                                                    Bullying     0.3     0.5       0
15                                             Family Matters      5.9     5.4     6.5
16                                                      Others     0.4     0.5     0.2

###DF11 cleaning

In [ ]:
print(df11.to_string())

          Age Group Population aged 3 to 24 Years  CA_M&F    CA_M    CA_F NCA_M&F  NCA_M  NCA_F
0             TOTAL                        46,746  31,943  16,131  15,812  14,803  7,896  6,907
1  Percent to Total                           100    68.3    34.5    33.8    31.7   16.9   14.8
2             Total                           NaN     100     100     100     100    100    100
3           3 to 5                          6,769     5.1     5.2       5    34.7   34.2   35.3
4            6 to 9                         9,075    27.5    27.9      27     2.1    2.2      2
5          10 to 12                         6,497    19.7      20    19.4     1.4    1.6    1.2
6          13 to 14                         4,302    12.9    12.9    12.9     1.3    1.6    0.9
7          15 to 16                         4,304    12.3    12.1    12.5     2.5    3.2    1.8
8          17 to 19                         6,037    14.4    13.8    14.9     9.8   10.7    8.7
9          20 to 24                         9,764     8.2     8.2     8.3    48.2   46.6   50.1

In [ ]:
#remove irrelevant and redundant row with null value
df11.dropna(inplace = True)

In [ ]:
#display cleaned df11
print(df11.to_string())

          Age Group Population aged 3 to 24 Years  CA_M&F    CA_M    CA_F NCA_M&F  NCA_M  NCA_F
0             TOTAL                        46,746  31,943  16,131  15,812  14,803  7,896  6,907
1  Percent to Total                           100    68.3    34.5    33.8    31.7   16.9   14.8
3           3 to 5                          6,769     5.1     5.2       5    34.7   34.2   35.3
4            6 to 9                         9,075    27.5    27.9      27     2.1    2.2      2
5          10 to 12                         6,497    19.7      20    19.4     1.4    1.6    1.2
6          13 to 14                         4,302    12.9    12.9    12.9     1.3    1.6    0.9
7          15 to 16                         4,304    12.3    12.1    12.5     2.5    3.2    1.8
8          17 to 19                         6,037    14.4    13.8    14.9     9.8   10.7    8.7
9          20 to 24                         9,764     8.2     8.2     8.3    48.2   46.6   50.1

## Exploratory Analysis and Visualization

###Total Live Births 1970-2019
- Used the columns of year and number of live births due to their strong relationship.
- Get the top 50 latest records and add in the year 2019 and the total live birhts of that year.
- Take a closer look on the years before, during, and after sex education  was implemented which was on 2012 to see its effects.

In [ ]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#mapping out the data set to see the correlation between each column
#this shows that there is a high correlation between Year and Population, Year and Number of Live Births, Birth Increase/ Decrease and Percentage Change
#we will be using the correlation between Year and Number of Live Births because of the following data sets which are connected with the Number of Live Births
df1.corr()
plt.figure(figsize=(8,8))
sns.heatmap(df1.corr(), annot = True, cmap ="coolwarm")
plt.savefig('fig1.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

In [ ]:
print(df1.to_string())

In [ ]:
#get the 50 latest values from the Yr and # of L.Births columns.
df1_Yr = df1.loc[:50:, 'Yr']
df1_Births = df1.loc[:50:, '# of L.Births']
df1_LBirths = df1_Births.astype('int64')
print(df1_Yr)
print(df1_LBirths)

In [ ]:
#create an array for the values to plot (add yr 2019 and # of L.Births of 2019)
#used data from 1970-2018(+2019)
#total live births from 1970 - 2019
xpoints = np.array([1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019])
ypoints = np.array([966762,963749,968385,1049290,1081073,1223837,1314860,1344836,1387588,1429814,1456860,1461204,1474491,1506356,1478205,1437154,1493995,1582469,1565372,1565254,1631069,1643296,1684395,1645011,1645043,1608468,1653236,1632859,1613335,1766440,1714093,1666773,1669442,1710994,1688918,1663029,1749878,1784316,1745584,1782981,1746684,1790367,1761602,1748857,1744767,1731289,1700618,1668120,1673923])

sns.lineplot(x = xpoints, y = ypoints, marker = 'o')
sns.set(rc = {'figure.figsize':(10,7)})
plt.axvspan(1970,1980, facecolor ='#0e2433', alpha=.4)
plt.axvspan(1980,1990, facecolor ='#1c4966', alpha=.4)
plt.axvspan(1990,2000, facecolor ='#296d98', alpha=.4)
plt.axvspan(2000,2010, facecolor ='#3792cb', alpha=.4)
plt.axvspan(2010,2020, facecolor ='#45b6fe', alpha=.4)
plt.title('Number of Live Births (1970-2019)')
plt.xlabel('Year')
plt.ylabel('Number of Live Births(million)')
plt.savefig('fig2.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

In [ ]:
#SexEd in the Philippines was integrated in public schools on 2012
#get the 13 latest values from the Yr and # of L.Births columns to have a closer look at the years before and after 2012
df1_Yr = df1.loc[:13:, 'Yr']
df1_Births = df1.loc[:13:, '# of L.Births']
df1_LBirths = df1_Births.astype('int64')
print(df1_Yr)
print(df1_LBirths)

In [ ]:
#create an array for the values to plot (add yr 2019 and # of L.Births of 2019)
#Visible reduction of live births since then
xpoints = np.array([2005,2006,2007,2008,2009,2010,2011,2012])
ypoints = np.array([1688918,1663029,1749878,1784316,1745584,1782981,1746684,1790367])
y2points = np.array([1790367,1761602,1748857,1744767,1731289,1700618,1668120,1673923])
x2points = np.array([2012,2013,2014,2015,2016,2017,2018,2019])
sns.set(rc = {'figure.figsize':(10,7)})
plt.plot(xpoints, ypoints, marker = 'o')
plt.plot(x2points, y2points, color='red', marker = 'o')


plt.axvspan(2005,2012, facecolor ='#296d98', alpha=.4)
plt.axvspan(2012,2019, facecolor ='#3792cb', alpha=.4)
plt.title('Number of Live Births (2005-2019)')
plt.xlabel('Year')
plt.ylabel('Number of Live Births(million)')
plt.savefig('fig3.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

### Parents that had live Births from (2012-2019)
- Was supposed to show the number of live births from parents aged below 20 but the data set showed the number of parents for those live births instead.
- Showed the number of parents aged below 20 who had live births from 2012-2019 since the dataset showed parents of different ages.
- Not every live birth parent were both teenagers so only the ones aged below 20 were counted.

In [ ]:
print(df2.to_string())

In [ ]:
#get the total of teenage and adult parents from 2012-2019
df2_2012 = df2.iloc[1,1] + df2.iloc[1,2]
df3_2013 = df3.iloc[1,1] + df3.iloc[1,2]
df4_2014 = df4.iloc[1,1] + df4.iloc[1,2]
df5_2015 = df5.iloc [1,1] + df5.iloc [1,2] + df5.iloc [2,1] + df5.iloc [2,2]
df6_2016 = df6.iloc [1,1] + df6.iloc [1,2] + df6.iloc [2,1] + df6.iloc [2,2]
df7_2017 = df7.iloc [1,1] + df7.iloc [1,2] + df7.iloc [2,1] + df7.iloc [2,2]
df8_2018 = df8.iloc [1,1] + df8.iloc [1,2] + df8.iloc [2,1] + df8.iloc [2,2]
df9_2019 = df9.iloc [1,1] + df9.iloc [1,2] + df9.iloc [2,1] + df9.iloc [2,2]

df1_2012_2019 = df1.loc[:6:,'# of L.Births'].astype('int64')

print(df2_2012,df3_2013,df4_2014,df5_2015,df6_2016,df7_2017,df8_2018,df9_2019)
print(df1_2012_2019)

In [ ]:
#plot in bar graph
#number of parents who had live births from 2012-2019
X = [2012,2013,2014,2015,2016,2017,2018,2019]
Under_20 = [260216,262094,381843,260619,255155,248820,234161,233650]
#total # of live births * 2 = # of parents for the live births 2012-2019
Over_20 = [1790367*2,1761602*2,1748857*2,1744767*2,1731289*2,1700618*2,1668120*2,1673923*2]

plt.figure(figsize=(10,7))
sns.set_theme(style="whitegrid")
#total # of live births * 2 = # of parents for the live births 2012-2019
ax = sns.barplot(x=X, y = Over_20, data=df1, color = 'royalblue', label = 'Under 20', ec = 'midnightblue')
ax = sns.barplot(x=X, y = Under_20, color = 'lightcoral', label = '20 and Over', ec = 'midnightblue')

plt.title("Parents that had Live Births from 2012-2019")
plt.xlabel('Year')
plt.ylabel('Number of Parents (million)')
plt.legend(bbox_to_anchor=(1.02, 1))
plt.savefig('fig4.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

###Schooling Status
- To show that not every teenager can be exposed to sex education in the curriculum (flawed).

In [ ]:
print(df11.to_string())

In [ ]:
#get the values of currently and not currently attending population
status = df11.iloc[1,2] , df11.iloc[1,5]
print(status)

In [ ]:
#plot the chart from the data
#at least 1 in every 4 people in the population was not attending school
sns.set(rc = {'figure.figsize':(20,10)})
s_Status = [68.3,31.7]
labels = ['Currently Attending', 'Not Currently Attending']
colors = sns.color_palette('Paired')
mexplode = [0,0.1]
plt.pie(s_Status, colors = colors, labels=labels, autopct="%.1f%%", explode = mexplode)
plt.savefig('fig8.tiff', bbox_inches="tight",pad_inches=1, dpi=300)
plt.show()

In [ ]:
#age group percent distribution of those who were not currently attending school 
#majority of them are at the working age and not at school age yet
s_status = np.array([48.2,34.7,9.8+2.5+1.3+1.4,2.1])
Mlabels = ['20 to 24','3 to 5', '10 to 19','6 to 9']
sns.set(rc = {'figure.figsize':(20,10)})
fig,ax=plt.subplots()
Pcolor = sns.color_palette('Set2')
Explode = [0,0,0.2,0]
ax.pie (s_status, labels = Mlabels, colors = Pcolor, autopct="%.1f%%", explode = Explode)
plt.legend(bbox_to_anchor=(0.8, 0.9))
plt.savefig('fig9.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

###Current Use of Contraception

In [ ]:
print(df12.to_string())

In [ ]:
#get the data from specific columns and rows
anymethod = df12.loc[:6:,'Any method']
not_using = df12.loc[:6:,'Not currently using']
pill = df12.loc[:6:,'Pill']
withdrawal = df12.loc[:6:, 'Withdrawal']
wmn = df12.loc[:6:, 'Number of Women']

print(anymethod,not_using,pill,withdrawal,wmn)

In [ ]:
#plot the graph from the data
#age group 15-19 has the highest percentage that do not use any contraceptives almost tying with the 45-49 age group
#age group 15-49 is also the lowest among the age groups who uses any method of contraception almost tying again with age group 45-49
x = ['15-19\n(419)','20-24\n(1718)','25-29\n(2628)','30-34\n(2663)','35-39\n(2775)','40-44\n(2443)','45-49\n(2372)']
using = [35.8,55.7,56.6,61.9,59.8,55.55,37.6]
not_using =[64.2,44.3,43.4,38.1,40.2,44.5,62.4]
women = [419,1718,2628,2663,2775,2443,2372]
x_axis = np.arange(len(x))
plt.figure(figsize=(10,8))
NCUcolor = ['cornflowerblue','cornflowerblue','cornflowerblue','cornflowerblue','cornflowerblue','cornflowerblue','cornflowerblue',]
UAMcolor = ['lightsteelblue','lightsteelblue','lightsteelblue','lightsteelblue','lightsteelblue','lightsteelblue','lightsteelblue',]
topNCUcolor = ['cornflowerblue','lightgray','lightgray','lightgray','lightgray','lightgray','cornflowerblue',]
topUAMcolor = ['lightsteelblue','lightgray','lightgray','lightgray','lightgray','lightgray','lightsteelblue',]
plt.bar(x_axis - 0.2, not_using, 0.4, ec = 'black', label = 'Not Currently Using', color = NCUcolor)
plt.bar(x_axis + 0.2, using, 0.4, ec = 'black', label = 'Uses Any method', color = UAMcolor)

plt.xticks(x_axis,x)
plt.title('Current Use of Contraception')
plt.xlabel('Age Group')
plt.ylabel('Percentage from Population (%)')
plt.legend(bbox_to_anchor=(1.02, 1))

for i in range(len(x)):
  plt.text(i, using[i], using[i], ha='left', va='bottom')
  plt.text(i, not_using[i], not_using[i], ha='right', va='bottom')

plt.savefig('fig5.tiff', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

In [ ]:
#top contraceptive method from modern and traditional methods
x = ['15-19\n(419)','20-24\n(1718)','25-29\n(2628)','30-34\n(2663)','35-39\n(2775)','40-44\n(2443)','45-49\n(2372)']
pill = [16.0,27.6,25.8,27.7,22.0,17.1,6.6]
withdrawal = [5.4,9.4,11.1,12.5,10.9,10.4,7.8]
plt.figure(figsize=(10,8))
x_axis = np.arange(len(x))


plt.bar(x_axis + 0.2, pill, 0.4, ec = 'black', label = 'Using Pills', color ='cornflowerblue')
plt.bar(x_axis - 0.2, withdrawal, 0.4, ec = 'black', label = 'Withdrawal', color ='lightsteelblue')

for i in range(len(x)):
  plt.text(i, pill[i], pill[i], ha='left', va='bottom')
  plt.text(i, withdrawal[i], withdrawal[i], ha='right', va='bottom')

plt.xticks(x_axis,x)
plt.title('Top Modern and Traditional Contraception Method')
plt.xlabel('Age Group')
plt.ylabel('Percentage from Population (%)')
plt.legend(bbox_to_anchor=(1.02, 1))
plt.savefig('fig6.tiff', bbox_inches="tight",pad_inches=1,dpi = 300)
plt.show()

###Knowledge of HIV prevention methods

In [ ]:
print(df13.to_string())

In [ ]:
#get the data from the prevention methods columns
options = df13.loc[1:5:,['Using condoms','Limiting sexual intercourse to one uninfected partner','Using condoms and limiting sexual intercourse to one uninfected partner']]
options

In [ ]:
#plot the graph from the data
#the age group 15-19 had the lowest knowledge about HIV prevention methods overall
age = ['15-19\n(4897)','20-24\n(4175)','25-29\n(3717)','30-39\n(6603)','40-49\n(5682)']
option1 = [52.9,66.5,68.8,71.0,70.4]
option2 = [74.2,84.3,86.5,88.3,85.5]
option3 = [48.1,62.3,65.5,67.9,66.1]
x_axis = np.arange(len(age))
plt.figure(figsize=(20,10))

plt.bar(x_axis - 0.2, option1, 0.4, ec = 'black', label = 'Use of condoms')
plt.bar(x_axis + 0.2, option2, 0.4, ec = 'black', label = 'Limiting SI to One Uninfected Partner')
plt.bar(x_axis, option3, 0.5, ec = 'black', label = 'Both')

plt.xticks(x_axis,age)
plt.title('Knowledge about HIV Prevention methods')
plt.xlabel('Age Group')
plt.ylabel('Percentage from Population (%)')
plt.legend(bbox_to_anchor=(1.02, 1))
HIVcolor = sns.color_palette('Set2')
for i in range(len(age)):
  plt.text(i, option1[i], option1[i], ha='right', va='bottom')
  plt.text(i, option2[i], option2[i], ha='left', va='bottom')
  plt.text(i, option3[i], option3[i], ha='left', va='bottom')
plt.savefig('fig7.png', bbox_inches="tight",pad_inches=1, dpi = 300)
plt.show()

# Ask & Answer Questions
1. How much do the teenage parents contribute to the total parents from 2012-2019?
- 2012 = 260216 / 3580734 = 7.27 %
- 2013 = 262094 / 3523204 = 7.44 %
- 2014 = 381843 / 3497714 = 10.92 %
- 2015 = 260619 / 3489534 = 7.47 %
- 2016 = 255155 / 3462578 = 7.37 %
- 2017 = 248820 / 3401236 = 7.32 %
- 2018 = 234161 / 3336240 = 7.02 %
- 2019 = 233650 / 3347846 = 6.98 %
2. What is the percentage of the population that did not attend school?
- 31.7% (4588.93 x 1000 = 4,588,930)
3. What was the percentage of the population who's reason was pregnancy?
- 1.6 % (154.69 x 1000 = 154,690 )
4. How much of the population used contraception?
- 15-19 = 64.2 or 267.00
- 20-24 = 44.3 or 761.07
- 25-29 = 43.4 or 1140.55
- 30-34 = 38.1 or 1014.60
- 35-39 = 40.2 or 1115.55
- 40-44 = 44.5 or 1087.14
- 45-49 = 62.4 or 1480.13
5. Which age group had the biggest percentage of that did not use contraceptives?
- 15-19
6. How much of the population knew both of the mentioned HIV prevention methods?
- 15-19 = 48.1 or 2355.46
- 20-24 = 62.3 or 2601.03
- 25-29 = 65.5 or 2434.64
- 30-39 = 67.9 or 4483.44
- 40-49 = 66.1 or 3755.80

# SAVE

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Execute this to save new versions of the notebook
jovian.commit(project="implementation-of-sex-education")